apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: iskoces-models
  namespace: iskoces
  labels:
    app.kubernetes.io/name: iskoces
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  # OpenShift will use the default storage class if not specified
  # For production, specify a storage class if needed:
  # storageClassName: gp3-csi

