apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: iskoces-models
  namespace: iskoces
  labels:
    app.kubernetes.io/name: iskoces
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  # Use lvms-vg1 storage class (topolvm.io provisioner)
  # This is the available storage class in this OpenShift cluster
  storageClassName: lvms-vg1

